[package]
name = "quick_gh_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0", features = ["derive"] }
structopt = "0.3.21"
exitfailure = "0.5.1"
indicatif = "0.16.2"
reqwest = { version = "0.11.0", features = ["json"] }
serde = "1.0.119"
serde_json = "1.0.61"
serde_derive = "1.0.119"
tokio = { version = "1.0.2", features = ["full"] }
dirs-next = "2.0.0"
confy = "0.4.0"
